// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/policy/v1/policy.proto

package policypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EvaluateRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserId            string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount            string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency          string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Asset             string                 `protobuf:"bytes,4,opt,name=asset,proto3" json:"asset,omitempty"`
	Rail              string                 `protobuf:"bytes,5,opt,name=rail,proto3" json:"rail,omitempty"`
	DestAddress       string                 `protobuf:"bytes,6,opt,name=dest_address,json=destAddress,proto3" json:"dest_address,omitempty"`
	DestChain         string                 `protobuf:"bytes,7,opt,name=dest_chain,json=destChain,proto3" json:"dest_chain,omitempty"`
	KytVerdict        string                 `protobuf:"bytes,8,opt,name=kyt_verdict,json=kytVerdict,proto3" json:"kyt_verdict,omitempty"`
	FraudScore        float64                `protobuf:"fixed64,9,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	KycStatus         string                 `protobuf:"bytes,10,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	UserTier          string                 `protobuf:"bytes,11,opt,name=user_tier,json=userTier,proto3" json:"user_tier,omitempty"`
	Session_2FaPassed bool                   `protobuf:"varint,12,opt,name=session_2fa_passed,json=session2faPassed,proto3" json:"session_2fa_passed,omitempty"`
	FxRateToUsd       float64                `protobuf:"fixed64,13,opt,name=fx_rate_to_usd,json=fxRateToUsd,proto3" json:"fx_rate_to_usd,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_proto_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluateRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *EvaluateRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *EvaluateRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *EvaluateRequest) GetRail() string {
	if x != nil {
		return x.Rail
	}
	return ""
}

func (x *EvaluateRequest) GetDestAddress() string {
	if x != nil {
		return x.DestAddress
	}
	return ""
}

func (x *EvaluateRequest) GetDestChain() string {
	if x != nil {
		return x.DestChain
	}
	return ""
}

func (x *EvaluateRequest) GetKytVerdict() string {
	if x != nil {
		return x.KytVerdict
	}
	return ""
}

func (x *EvaluateRequest) GetFraudScore() float64 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *EvaluateRequest) GetKycStatus() string {
	if x != nil {
		return x.KycStatus
	}
	return ""
}

func (x *EvaluateRequest) GetUserTier() string {
	if x != nil {
		return x.UserTier
	}
	return ""
}

func (x *EvaluateRequest) GetSession_2FaPassed() bool {
	if x != nil {
		return x.Session_2FaPassed
	}
	return false
}

func (x *EvaluateRequest) GetFxRateToUsd() float64 {
	if x != nil {
		return x.FxRateToUsd
	}
	return 0
}

type AppliedRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppliedRule) Reset() {
	*x = AppliedRule{}
	mi := &file_proto_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppliedRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppliedRule) ProtoMessage() {}

func (x *AppliedRule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppliedRule.ProtoReflect.Descriptor instead.
func (*AppliedRule) Descriptor() ([]byte, []int) {
	return file_proto_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *AppliedRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppliedRule) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type EvaluateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      string                 `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	Reasons       []string               `protobuf:"bytes,2,rep,name=reasons,proto3" json:"reasons,omitempty"`
	AppliedRules  []*AppliedRule         `protobuf:"bytes,3,rep,name=applied_rules,json=appliedRules,proto3" json:"applied_rules,omitempty"`
	PolicyVersion string                 `protobuf:"bytes,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	DecisionId    string                 `protobuf:"bytes,6,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_proto_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *EvaluateResponse) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

func (x *EvaluateResponse) GetAppliedRules() []*AppliedRule {
	if x != nil {
		return x.AppliedRules
	}
	return nil
}

func (x *EvaluateResponse) GetPolicyVersion() string {
	if x != nil {
		return x.PolicyVersion
	}
	return ""
}

func (x *EvaluateResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EvaluateResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

var File_proto_policy_v1_policy_proto protoreflect.FileDescriptor

const file_proto_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/policy/v1/policy.proto\x12\tpolicy.v1\"\x9b\x03\n" +
	"\x0fEvaluateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x14\n" +
	"\x05asset\x18\x04 \x01(\tR\x05asset\x12\x12\n" +
	"\x04rail\x18\x05 \x01(\tR\x04rail\x12!\n" +
	"\fdest_address\x18\x06 \x01(\tR\vdestAddress\x12\x1d\n" +
	"\n" +
	"dest_chain\x18\a \x01(\tR\tdestChain\x12\x1f\n" +
	"\vkyt_verdict\x18\b \x01(\tR\n" +
	"kytVerdict\x12\x1f\n" +
	"\vfraud_score\x18\t \x01(\x01R\n" +
	"fraudScore\x12\x1d\n" +
	"\n" +
	"kyc_status\x18\n" +
	" \x01(\tR\tkycStatus\x12\x1b\n" +
	"\tuser_tier\x18\v \x01(\tR\buserTier\x12,\n" +
	"\x12session_2fa_passed\x18\f \x01(\bR\x10session2faPassed\x12#\n" +
	"\x0efx_rate_to_usd\x18\r \x01(\x01R\vfxRateToUsd\"7\n" +
	"\vAppliedRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xe3\x01\n" +
	"\x10EvaluateResponse\x12\x1a\n" +
	"\bdecision\x18\x01 \x01(\tR\bdecision\x12\x18\n" +
	"\areasons\x18\x02 \x03(\tR\areasons\x12;\n" +
	"\rapplied_rules\x18\x03 \x03(\v2\x16.policy.v1.AppliedRuleR\fappliedRules\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\tR\rpolicyVersion\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x12\x1f\n" +
	"\vdecision_id\x18\x06 \x01(\tR\n" +
	"decisionId2O\n" +
	"\x06Policy\x12E\n" +
	"\bEvaluate\x12\x1a.policy.v1.EvaluateRequest\x1a\x1b.policy.v1.EvaluateResponse\"\x00BIZGgithub.com/ai-crypto-onramp/policy-risk-engine/proto/policy/v1;policypbb\x06proto3"

var (
	file_proto_policy_v1_policy_proto_rawDescOnce sync.Once
	file_proto_policy_v1_policy_proto_rawDescData []byte
)

func file_proto_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_proto_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_proto_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policy_v1_policy_proto_rawDesc), len(file_proto_policy_v1_policy_proto_rawDesc)))
	})
	return file_proto_policy_v1_policy_proto_rawDescData
}

var file_proto_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_policy_v1_policy_proto_goTypes = []any{
	(*EvaluateRequest)(nil),  // 0: policy.v1.EvaluateRequest
	(*AppliedRule)(nil),      // 1: policy.v1.AppliedRule
	(*EvaluateResponse)(nil), // 2: policy.v1.EvaluateResponse
}
var file_proto_policy_v1_policy_proto_depIdxs = []int32{
	1, // 0: policy.v1.EvaluateResponse.applied_rules:type_name -> policy.v1.AppliedRule
	0, // 1: policy.v1.Policy.Evaluate:input_type -> policy.v1.EvaluateRequest
	2, // 2: policy.v1.Policy.Evaluate:output_type -> policy.v1.EvaluateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_policy_v1_policy_proto_init() }
func file_proto_policy_v1_policy_proto_init() {
	if File_proto_policy_v1_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policy_v1_policy_proto_rawDesc), len(file_proto_policy_v1_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_proto_policy_v1_policy_proto_depIdxs,
		MessageInfos:      file_proto_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_proto_policy_v1_policy_proto = out.File
	file_proto_policy_v1_policy_proto_goTypes = nil
	file_proto_policy_v1_policy_proto_depIdxs = nil
}
